<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.11.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NovaDB.Commands\NovaDB.Commands.csproj" />
    <ProjectReference Include="..\..\src\NovaDB.Configuration\NovaDB.Configuration.csproj" />
    <ProjectReference Include="..\..\src\NovaDB.Core\NovaDB.Core.csproj" />
    <ProjectReference Include="..\..\src\NovaDB.Networking\NovaDB.Networking.csproj" />
    <ProjectReference Include="..\..\src\NovaDB.Protocol\NovaDB.Protocol.csproj" />
    <ProjectReference Include="..\..\src\NovaDB.PubSub\NovaDB.PubSub.csproj" />
    <ProjectReference Include="..\..\src\NovaDB.Storage\NovaDB.Storage.csproj" />
    <ProjectReference Include="..\..\src\NovaDB.Transactions\NovaDB.Transactions.csproj" />
    <ProjectReference Include="..\..\src\NovaDB.Persistence\NovaDB.Persistence.csproj" />
  </ItemGroup>

</Project>